# Build-Stage: Angular bauen
FROM node:20 AS build
WORKDIR /app/frontend

# Dependencies installieren
COPY frontend/package*.json ./
COPY h5p-standalone /app/h5p-standalone
RUN npm install --ignore-scripts

# Restlichen Code kopieren
COPY frontend/ ./

# Angular-Build ausführen (nutzt deine angular.json, default config = production)
RUN npm run build

# Serve-Stage: Nginx als Webserver
FROM nginx:stable-alpine

# Nginx-Default-Inhalt löschen
RUN rm -rf /usr/share/nginx/html/*

# Gebaute Dateien aus dist/frontend/browser nach /usr/share/nginx/html kopieren
COPY --from=build /app/frontend/dist/frontend/browser/ /usr/share/nginx/html/

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
