services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app/frontend
      - ./h5p-standalone:/app/h5p-standalone
      - /app/frontend/node_modules
    container_name: angular-frontend
    command: npm start

  express:
    build: ./express
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
    ports:
      - "3000:3000"
    volumes:
      - ./express:/app
      - /app/node_modules
    container_name: express-backend
    depends_on:
      - pocketbase
    command: npm run dev # Wenn Sie nodemon verwenden, sonst node index.js


  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data
      - ./pocketbase/pb_migrations:/pb_migrations
    container_name: pocketbase-db
